"use client";

import { useEffect, useState } from "react";
import { convertirEnEur } from "@/lib/localisation";

type Profil = {
  id: string;
    nom: string;
      seniorite: string | null;
        anneesExperience: number | null;
          tjmEstime: number | null;
            disponibilite: string | null;
              nationalite: string | null;
                paysResidence: string | null;
                  paysResidencePrecision: string | null;
                    regimeSuggere: string | null;
                      tjmSouhaite: number | null;
                        tjmSouhaiteDevise: string | null;
                        };

                        // Vue d'ensemble des profils d'ingenieurs valides, pensee pour le matching :
                        // pour un meme besoin client, permet de comparer en un coup d'oeil le TJM
                        // estime du profil et la pretention salariale (TJM souhaite) declaree par
                        // l'ingenieur - dans sa devise d'origine, convertie en euros a titre
                        // indicatif - afin de reperer les profils les plus competitifs selon leur
                        // pays de residence (voir lib/localisation.ts).
                        export default function ProfilsPage() {
                          const [profils, setProfils] = useState<Profil[]>([]);
                            const [chargement, setChargement] = useState(true);

                              useEffect(() => {
                                  fetch("/api/profils")
                                        .then((r) => r.json())
                                              .then((data) => {
                                                      setProfils(Array.isArray(data) ? data : []);
                                                              setChargement(false);
                                                                    });
                                                                      }, []);

                                                                        if (chargement) {
                                                                            return <div>Chargement...</div>;
                                                                              }

                                                                                return (
                                                                                    <div>
                                                                                          <h1>Profils</h1>
                                                                                                <p style={{ fontSize: 13, color: "#666", marginBottom: 16, maxWidth: 720 }}>
                                                                                                        TJM estime = analyse interne du profil (seniorite, competences). TJM souhaite = pretention declaree par
                                                                                                                l'ingenieur, dans la devise de son choix ; la conversion en euros est indicative (taux fixes, non
                                                                                                                        connectes a un service de change en temps reel) et sert uniquement a comparer les profils entre eux.
                                                                                                                              </p>
                                                                                                                                    <div style={{ overflowX: "auto" }}>
                                                                                                                                            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 14 }}>
                                                                                                                                                      <thead>
                                                                                                                                                                  <tr style={{ textAlign: "left", borderBottom: "1px solid #ddd" }}>
                                                                                                                                                                                <th style={{ padding: "6px 8px" }}>Ingenieur</th>
                                                                                                                                                                                              <th style={{ padding: "6px 8px" }}>Seniorite</th>
                                                                                                                                                                                                            <th style={{ padding: "6px 8px" }}>Pays de residence</th>
                                                                                                                                                                                                                          <th style={{ padding: "6px 8px" }}>Disponibilite</th>
                                                                                                                                                                                                                                        <th style={{ padding: "6px 8px" }}>TJM estime</th>
                                                                                                                                                                                                                                                      <th style={{ padding: "6px 8px" }}>TJM souhaite</th>
                                                                                                                                                                                                                                                                    <th style={{ padding: "6px 8px" }}>EUR (indicatif)</th>
                                                                                                                                                                                                                                                                                  <th style={{ padding: "6px 8px" }}>Comparaison</th>
                                                                                                                                                                                                                                                                                                <th style={{ padding: "6px 8px" }}>Profil suggere</th>
                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                      </thead>
                                                                                                                                                                                                                                                                                                                                <tbody>
                                                                                                                                                                                                                                                                                                                                            {profils.map((p) => (
                                                                                                                                                                                                                                                                                                                                                          <LignProfil key={p.id} p={p} />
                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                </tbody>
                                                                                                                                                                                                                                                                                                                                                                                        </table>
                                                                                                                                                                                                                                                                                                                                                                                                {profils.length === 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                          <p style={{ fontSize: 13, color: "#888", marginTop: 12 }}>Aucun profil pour l'instant.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                              function LignProfil({ p }: { p: Profil }) {
                                                                                                                                                                                                                                                                                                                                                                                                                                const tjmSouhaiteEur =
                                                                                                                                                                                                                                                                                                                                                                                                                                    p.tjmSouhaite != null && p.tjmSouhaiteDevise ? convertirEnEur(p.tjmSouhaite, p.tjmSouhaiteDevise) : null;
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                      const comparaison = comparerTjm(p.tjmEstime, tjmSouhaiteEur);
                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr style={{ borderBottom: "1px solid #f0f0f0" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td style={{ padding: "6px 8px" }}>{p.nom}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td style={{ padding: "6px 8px" }}>{p.seniorite ?? "-"}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td style={{ padding: "6px 8px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {p.paysResidence === "Autre" ? p.paysResidencePrecision ?? "-" : p.paysResidence ?? "-"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td style={{ padding: "6px 8px" }}>{p.disponibilite ?? "-"}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td style={{ padding: "6px 8px" }}>{p.tjmEstime != null ? Math.round(p.tjmEstime) + " EUR" : "-"}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td style={{ padding: "6px 8px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {p.tjmSouhaite != null ? `${p.tjmSouhaite} ${p.tjmSouhaiteDevise ?? ""}`.trim() : "-"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td style={{ padding: "6px 8px" }}>{tjmSouhaiteEur != null ? "~ " + tjmSouhaiteEur + " EUR" : "-"}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td style={{ padding: "6px 8px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: 600,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: comparaison.couleur,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {comparaison.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td style={{ padding: "6px 8px", fontSize: 12, color: "#666", maxWidth: 260 }}>{p.regimeSuggere ?? "-"}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function comparerTjm(tjmEstime: number | null, tjmSouhaiteEur: number | null): { label: string; couleur: string } {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (tjmEstime == null || tjmSouhaiteEur == null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return { label: "Analyse non disponible", couleur: "#9aa0ab" };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const ratio = tjmSouhaiteEur / tjmEstime;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (ratio <= 1.15) return { label: "Coherent", couleur: "#16a34a" };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (ratio <= 1.4) return { label: "A negocier", couleur: "#d97706" };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return { label: "Ecart important", couleur: "#dc2626" };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
